### ISSUE TITLE
Cannot assign requested address 

### ISSUE THREAD

**Issue by Rover17-Dev** [Hebbinkpro/pmmp-webserver#1]
Hello
I am trying to use the plugin in my server all seems well but the webserver cannot be accessed.

My server is running in a Pterodactyl panel and I had to allocate a second port to my server.
But I can still not acces to the webserver
In addition I tried to change the ip (127.0.0.1) by the ip that I have as allocated and now the webserver crashes with this error "Cannot assign requested address "

Thank you

**Comment by Hebbinkpro** [comment]
Hey,
Have you tried going to `http://<your_pocketmine_server_ip>:<web_server_port>/` with the address of the web server set  to `127.0.0.1`?

**Comment by Rover17-Dev** [comment]
Yes I have tried it.
Is this plugin working with a server running under pterodactyl panel ?

**Comment by Hebbinkpro** [comment]
I've not yet tested the plugin on a Pterodactyl server.
I assume that you have set the web server port to the second port that is allocated to the server, if this isn't the case you have to do that. If it is, then its probably an issue with the webserver.

The plugin is still under development, so it's possible these issues occur. I will try to fix this issue in a future release of the plugin.

**Comment by Hebbinkpro** [comment]
I've tested it on a pterodactyl server and found the issue. You have to set the address of the web server to `0.0.0.0` and than it's fixed.
